In [2]:
#Exp : 5
#Aim : Creation of array using numpy

In [3]:
#Name : Arya Shashikant Deshmukh
#Roll no. : 7
#Section : B
#Batch : B1

In [4]:
import numpy as np

In [5]:
#Creation of 1D array

In [6]:
arr1 = np.array([1,2,3,4,5])

In [7]:
print(arr1)

[1 2 3 4 5]


In [8]:
#Creation of 2D array

In [9]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [10]:
print(arr2)

[[1 2 3]
 [4 5 6]]
